services:
  projekt_prog_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - LOG_LEVEL=INFO
    ports:
      - 5000:5000